### ISSUE TITLE
advice regarding combined locks (locking 2 or more resources)

### ISSUE THREAD

**Issue by jokeyrhyme** [jamestalmage/exclusive-task#1]
Very interesting project!

I'm working on a project that has many small tasks: https://github.com/jokeyrhyme/node-init
I have a few tasks that read/write to package.json, a few that write to README.md, etc. The tasks don't really depend on each other, but I don't want 2 package.json tasks to execute concurrently.

Some of the tasks depend on multiple resources, and can't be further divided into single-resource tasks. So I'd need, for example, a task that locks both package.json and README.md.

Any ideas on how I might use gulp-lock to wrangle this mess of tasks?

**Comment by jamestalmage** [comment]
Well, you could try something like this:

``` js
var lock1 = lock();
var lock2 = lock();

gulp.task('foo', lock1.promise(lock2.promise(function () {
  // perform the task
}));
```

When you combine locks like this, you should definitely do it in the same order every time.

Do **NOT** do the following:

``` js
gulp.task('foo', lock1.promise(lock2.promise(function () {
  // perform the task
}));

// note that the lock order is reversed. -- RACE CONDITIONS!
gulp.task('foo', lock2.promise(lock1.promise(function () {
  // perform the task
}));
```

**Comment by jokeyrhyme** [comment]
Thanks, I'll give that a try. :)

**Comment by jokeyrhyme** [comment]
I'll consider this answersed for now, thanks. I'll re-open / reply if I have any further questions / feedback. Thanks!
